services:
  - type: web
    name: wedding-bot
    env: python
    plan: free
    python:
      version: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8241053303:AAH8asphJN8vSXjNdiVSmEPXgnIfEwp2Dp0
